### ISSUE TITLE
專案缺少api key

### ISSUE THREAD

**Issue by iggh966380** [SeijoHuang/Movie-forum#3]
問題已解決

**Comment by SeijoHuang** [comment]
Hi~阿杰

抱歉⋯過了1個多月，我才看到這封mail，沒能即時回覆你，真的感到很抱歉QQ
很感謝當時你幫忙回答跟找問題！！
這個作品目前已經順利完成了～～

之後在布魯斯前端群組也請多多指教：）

Seijo

iggh966380 ***@***.***>於 2022年8月2日 週二，22:03寫道：
